export const SET_NAME = 'GAME:SET_PLAYER_NAME';

export const FETCH_QUESTIONS = 'QUESTION:FETCH_QUESTION';

export const SHOW_ALERT = 'ALERT:SHOW_ALERT';
export const HIDE_ALERT = 'ALERT:HIDE_ALERT';
