//GAME
export const SET_NAME = 'GAME:SET_PLAYER_NAME';
export const RESET_SCORE = 'GAME:RESET_SCORE';
export const RESET_PRIZE_POOL = 'GAME:RESET_PRIZE_POOL';
export const RESET_LIVES = 'GAME:RESET_LIVES';
export const RESET_SKIPS = 'GAME:RESET_SKIPS';
export const DOUBLE_PRIZE_POOL = 'GAME:DOUBLE_PRIZE_POOL';
export const INCREASE_SCORE = 'GAME:INCREASE_SCORE';
export const LOSE_LIFE = 'GAME:LOSE_LIFE';
export const LOSE_SKIP = 'GAME:LOSE_SKIP';
export const END_GAME = 'GAME:END_GAME';
//QUESTIONS
export const FETCH_QUESTIONS = 'QUESTIONS:FETCH_QUESTIONS';
export const UPDATE_QUESTIONS = 'QUESTIONS:UPDATE_QUESTIONS';
export const FETCH_THEMES = 'QUESTIONS:FETCH_THEMES';
export const SET_THEME = 'QUESTIONS:SET_THEME';
export const SET_QUESTION = 'QUESTIONS:SET_QUESTION';
export const SHOW_LOADER = 'QUESTIONS:SHOW_LOADER';
export const HIDE_LOADER = 'QUESTIONS:HIDE_LOADER';
//ALERT
export const SHOW_ALERT = 'ALERT:SHOW_ALERT';
export const HIDE_ALERT = 'ALERT:HIDE_ALERT';
//MODAL
export const SHOW_MODAL = 'MODAL:SHOW_MODAL';
export const HIDE_MODAL = 'MODAL:HIDE_MODAL';
//DISPLAY
export const SHOW_MESSAGE = 'DISPLAY:SHOW_MESSAGE';
export const HIDE_MESSAGE = 'DISPLAY:HIDE_MESSAGE';
