export const SET_NAME = 'GAME:SET_PLAYER_NAME';

export const FETCH_QUESTIONS = 'QUESTION:FETCH_QUESTION';
export const UPDATE_QUESTIONS = 'QUESTION:UPDATE_QUESTIONS';
export const SET_THEME = 'QUESTION:SET_THEME';
export const SET_QUESTION = 'QUESTION:SET_QUESTION';

export const SHOW_ALERT = 'ALERT:SHOW_ALERT';
export const HIDE_ALERT = 'ALERT:HIDE_ALERT';
